name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: swift build
      run: swift build
