name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 11"
          - "platform=tvOS Simulator,name=Apple TV"
          - "platform=watchOS Simulator,name=Apple Watch Series 6 (40mm)"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme SwiftTreeSitter -destination "${{ matrix.destination }}" test | xcpretty
