name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 11"
          - "platform=tvOS Simulator,name=Apple TV"
          - "platform=watchOS Simulator,name=Apple Watch Series 6 (40mm)"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install XCBeautify
        run: brew install xcbeautify
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme SwiftTreeSitter -destination "${{ matrix.destination }}" test | xcbeautify --renderer github-actions

  linux_test:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install swiftly
        run: curl -L https://swift-server.github.io/swiftly/swiftly-install.sh | bash -s -- -y
      - name: Install the latest Swift toolchain
        run: swiftly install latest
      - name: Build and run the unit tests
        run: swift test
