name: WebAssembly CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: WASM support
    runs-on: ubuntu-latest
    container: ghcr.io/swiftwasm/carton:0.17.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Work around to avoid this issue: https://github.com/ChimeHQ/SwiftTreeSitter/issues/8
      # We are running wasm-opt -O before execute the test for avoiding maximum of locals
      - name: Test WebAssembly
        run: |
          swift build -c debug --product SwiftTreeSitterPackageTests -Xswiftc -color-diagnostics --triple wasm32-unknown-wasi
          wasm-opt -O .build/wasm32-unknown-wasi/debug/SwiftTreeSitterPackageTests.wasm -o SwiftTreeSitterPackageTests.wasm
          wasmer SwiftTreeSitterPackageTests.wasm

